name: Build

on:
  push:
    paths:
      - 'app/**'
      - 'gradle/wrapper/gradle-wrapper.properties'
      - '*.gradle'
  workflow_dispatch:
    inputs:
      release:
        description: 'Upload to Release'
        type: boolean
        required: true
        default: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

      - name: Check out
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/dists
          key: ${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Build with Gradle
        run: | 
          ./gradlew assembleRelease
          echo "version=$(grep versionName ./app/build.gradle | awk '{print $2}' | tr -d \")" >> $GITHUB_ENV
          echo "commit=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_ENV

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Cpad_dcha_3_changer(Ver${{ env.version }}@${{ env.commit }})
          path: app/build/outputs/apk/release/app-release.apk

      - name: Re-signing APK
        if: github.event.inputs.release == 'true'
        run: |
          sudo apt-get install -y zipalign
          zip app/build/outputs/apk/release/app-release.apk -d "META-INF/com/android/build/gradle/app-metadata.properties"
          mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/app-release-unsigned.apk
          java -jar sign/signapk.jar sign/testkey.x509.pem sign/testkey.pk8 app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release-unaligned.apk
          zipalign 4 app/build/outputs/apk/release/app-release-unaligned.apk app/build/outputs/apk/release/app-release.apk

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.event.inputs.release == 'true'
        with:
          tag_name: Ver${{ env.version }}
          draft: true
          prerelease: false
          files: app/build/outputs/apk/release/app-release.apk
